POST https://puhelinluettelo-backend-c5do.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Pentti Aurinen",
    "number": "+358 45669972"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mauri Penttilä",
    "number": "+358 45969671"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Arto Hellas",
    "number":"040-123456"
}